### PR TITLE
Fixes #5 : Handle Response::sendHeaders() to not silently returns when header already sent

### LINKED ISSUE #5: `Zend\Http\Response\PhpEnvironment#sendHeaders()` silently returns - should scream and burn and demand for human sacrifices instead
https://github.com/zendframework/zend-http/blob/b382c6e068a2d9c87b7cf0dfe78c6dd19e4ff197/src/PhpEnvironment/Response.php#L84

To reproduce (sorry if I couldn't do it myself right away - needs a `@runInSeparateProcess` test):

```php
$response = new \Zend\Http\Response\PhpEnvironment();

echo 'foo;
ob_flush();

// expect an exception here
$response->sendHeaders();
```

---

Originally posted by @Ocramius at https://github.com/zendframework/zend-http/issues/138

### PR DESCRIPTION
**Pull request by samsonasik**
Signed-off-by: Abdul Malik Ikhsan <samsonasik@gmail.com>

|    Q          |   A
|-------------- | ------
| BC Break      | yes

### Description

Fixes https://github.com/laminas/laminas-http/issues/5 Handle Response::sendHeaders() to not silently returns when header already sent

### CODE REVIEW

**Comment by samsonasik** [comment]
travis build green :tada:

**Comment by Ocramius** [comment]
Given the stability of this library, I'm not sure if introducing this BC break at this point will be worth it though 🤔

File: src/PhpEnvironment/Response.php [hunk 1]
```diff
@@ -82,7 +83,7 @@ public function contentSent()
     public function sendHeaders()
     {
         if ($this->headersSent()) {
-            return $this;
+            throw new RuntimeException('Cannot send headers, headers already sent');
```
Comment (weierophinney) [inline src/PhpEnvironment/Response.php:86]: I tend to agree with @Ocramius that this would be a pretty egregious BC break.

One possibility that would resolve the issue as well as keep BC: we could add a "headers sent handler" callback to the response, and have it triggered here if it is present. Something like:

```php
private $headersSentHandler;

public function setHeadersSentHandler(?callable $handler): void
{
    $this->headersSentHandler = $handler;
}

public function sendHeaders()
{
    if ($this->headersSent()) {
        if ($this->headersSentHandler) {
            ($this->headersSentHandler)($this);
        }
        return;
    }

    // ...
```

If a user wants to throw an exception, they can either (a) add a delegator to the `Response` service, or (b - preferred) add a bootstrap listener that injects it:

```php
public function onBootstrap(MvcEvent $e): void
{
    $response = $e->getResponse();
    $response->setHeadersSentHandler(function ($response): void {
        throw new RuntimeException('Cannot send headers, headers already sent');
    });
}
```

This makes it opt-in, and, further, makes it easy for somebody to create a distributable module that enables the throw.

Comment (samsonasik) [reply src/PhpEnvironment/Response.php]: @weierophinney implemented.

**Comment by samsonasik** [comment]
travis build green 🎉

File: src/PhpEnvironment/Response.php [hunk 2]
```diff
@@ -74,6 +80,23 @@ public function contentSent()
         return $this->contentSent;
     }
 
+    /**
+     * @param callable $handler
+     */
+    public function setHeadersSentHandler($handler)
```
Comment (weierophinney) [inline src/PhpEnvironment/Response.php:86]: `callable` has been a valid typehint since at least 5.6, if not earlier; we should use it here. That way you don't even need to check the type within this method.

Also, document this as `@return void`, please.

File: src/PhpEnvironment/Response.php [hunk 3]
```diff
@@ -29,6 +30,11 @@ class Response extends HttpResponse
      */
     protected $contentSent = false;
 
+    /**
+     * @var callable
```
Comment (weierophinney) [inline src/PhpEnvironment/Response.php:34]:
```suggestion
     * @var null|callable
```

Because it's not set by default.

File: test/PhpEnvironment/ResponseTest.php [hunk 4]
```diff
@@ -100,4 +101,37 @@ public function testCanExplicitlySetVersion()
...
+        $response = new Response();
+        $this->assertInstanceOf(Response::class, $response->sendHeaders());
+    }
+
+    public function testSendHeadersHeadersAlreadySentPassInvalidHandler()
+    {
+        $this->expectException(InvalidArgumentException::class);
+        $this->expectExceptionMessage(
+            'Handler must be callable with passed response object in invokable parameter, received string'
+        );
```
Comment (weierophinney) [inline test/PhpEnvironment/ResponseTest.php:119]: The various `expectException*()` methods should be called immediately before the method call that is expected to raise them; otherwise, we may get a false positive if other statements raise the same errors. (This is true with your other tests as well.)

File: src/PhpEnvironment/Response.php (hunk 2 above)
Comment (samsonasik) [reply src/PhpEnvironment/Response.php]: implemented.

File: src/PhpEnvironment/Response.php (hunk 3 above)
Comment (samsonasik) [reply src/PhpEnvironment/Response.php]: implemented.

File: test/PhpEnvironment/ResponseTest.php (hunk 4 above)
Comment (samsonasik) [reply test/PhpEnvironment/ResponseTest.php]: implemented.

**Comment by samsonasik** [comment]
travis build green 🎉

**Comment by samsonasik** [comment]
@weierophinney  I've added documentation for it.

File: docs/book/response.md [hunk 5]
```diff
@@ -138,3 +138,16 @@ $response->setContent(<<<EOS
 </html>
 EOS);
 ```
+
+### handle Headers already sent
+
+Since 2.13.0, we can handle header already sent by pass callable via `Response::setHeadersSentHandler()`:
```
Comment (froschdesign) [inline docs/book/response.md:144]: ## Version hints

If a new feature was added with a minor release then a version hint must be added to the related section of the documentation page.
The hint must be added after the headline of the new feature.

## Syntax example

``````
> Available since version 2.13.0
``````

Comment (samsonasik) [reply docs/book/response.md:144]: What section that related? "Available Methods" part?

Comment (froschdesign) [reply docs/book/response.md:144]: @samsonasik 
> The hint must be added after the headline of the new feature.

Comment (samsonasik) [reply docs/book/response.md]: updated.

File: docs/book/response.md [hunk 6]
```diff
@@ -138,3 +138,16 @@ $response->setContent(<<<EOS
 </html>
 EOS);
 ```
+
+### handle Headers already sent
+
+> Available since version 2.13.0, we can handle header already sent by pass callable via `Response::setHeadersSentHandler()`:
```
Comment (froschdesign) [inline docs/book/response.md:144]:
```suggestion
> Available since version 2.13.0

We can handle header already sent by pass callable via `Response::setHeadersSentHandler()`:
```

The goal is to provide a consistent reference for the reader. See also:

* https://docs.laminas.dev/laminas-hydrator/v3/strategies/hydrator/
* https://docs.laminas.dev/laminas-inputfilter/optional-input-filters/

Comment (samsonasik) [reply docs/book/response.md]: thank you, applied.
