### PR TITLE
Provide PHP 8.1 support

### LINKED ISSUE #55: PHP 8.1: Countable incompatibility for Headers
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 2.14

#### Summary

PHP Fatal error:  During inheritance of Countable: Uncaught Return type of Laminas\Http\Headers::count() should either be compatible with Countable::count(): int, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice

More details can be found here:

https://php.watch/versions/8.1/serializable-deprecated
https://wiki.php.net/rfc/phase_out_serializable

#### Current behavior

Tests are failing.

#### How to reproduce

Execute tests with PHP 8.1

#### Expected behavior

Tests are passing.

### PR DESCRIPTION
**Pull request by weierophinney**
This patch provides support for PHP 8.1, via the following changes:

- Adds `~8.1.0` to the list of allowed PHP versions
- Changes how the package replaces zend-http
  - Renames the "replace" section in the packager to "conflict"
    - Changes the zend-http constraint to "*"
  - Removes the dependency on laminas-zendframework-bridge
- Removes dev requirement on laminas-config; testing can be done with vanilla `Traversable` classes.
- Bumps PHPUnit to 9.5 series
- Bumps laminas-stdlib, laminas-uri, laminas-loader, and laminas-validator dependencies to versions known to work with PHP 8.1
- Bumps laminas-coding-standard to 2.2 series, and applies the updated rulest
- Adds the `ReturnTypeWillChange` attribute to `Headers` methods implementing internal interfaces
- Provides a variety of small functionality fixes to work with PHP 8.1, primarily by using null coalesce to transform null return values to the appropriate type for `str*`, `preg_*`, and other internal methods.

### CODE REVIEW

File: src/Client.php [hunk 1]
```diff
@@ -998,24 +1016,26 @@ public function send(Request $request = null)
 
                 // Check whether we send the exact same request again, or drop the parameters
                 // and send a GET request
-                if ($response->getStatusCode() == 303
```
Comment (Ocramius) [inline src/Client.php:1001]: These `==` to `===` changes are a bit risky (all over the patch, BTW)

**Review by Ocramius — APPROVED** [review]
After more careful evaluation, I'd say that the changes from `==` to `===` are acceptable, and operate under the assumption that same-type inputs are provided.

These types match the documented input types (and therefore the API we cover/support).

:ship:
